name: "Cutting Lasagna"

resolve:
#  - "edge-point"

# The following motion phases will be executed in a sequence
motion-phases:
  - name: "Position Above"
    # Giskard file
    file: "cutting_position_above.yaml"
    # Stop conditions
    stop:
      # When measured gripper velocity drops below this threshold
      measured-velocity-min-threshold: 0.02
      # When desired (set by the controller) gripper velocity drops below this threshold
      desired-velocity-min-threshold: 0.02
      # Stop on contact
      contact: false
    # Ignore stop conditions until the distance 
    # from the target configuration is less than this
    stop-activation-distance: 0.15
  - name: "Cut"
    # Giskard file
    file: "cutting_cut.yaml"
    # Stop conditions
    stop:
      # When measured gripper velocity drops below this threshold
      measured-velocity-min-threshold: 0.002
      # When desired (set by the controller) gripper velocity drops below this threshold
      desired-velocity-min-threshold: 0.002
      # Stop on contact
      contact: false
    # Ignore stop conditions until the distance 
    # from the target configuration is less than this
    stop-activation-distance: 0.15
  - name: "Pull"
    # Giskard file
    file: "cutting_pull.yaml"
    # Stop conditions
    stop:
      # When measured gripper velocity drops below this threshold
      measured-velocity-min-threshold: 0.02
      # When desired (set by the controller) gripper velocity drops below this threshold
      desired-velocity-min-threshold: 0.02
      # Stop on contact
      contact: false
    # Ignore stop conditions until the distance 
    # from the target configuration is less than this
    stop-activation-distance: 0.15
