name: "Scooping"

required-object-info:
  tool: true
  target-object: true
  tool-task: scooping_grains
  target-object-task: scooping

# The following motion phases will be executed in a sequence
motion-phases:
  - name: "Position Above"
    # Giskard file
    file: "scooping_position_above.yaml"
    # Stop conditions
    stop:
      # When measured gripper velocity drops below this threshold
      measured-velocity-min-threshold: 0.02
      # When desired (set by the controller) gripper velocity drops below this threshold
      desired-velocity-min-threshold: 0.02
      # Stop on contact
      contact: true
      # Ignore stop conditions until the distance 
      # from the target configuration is less than this
      activation-distance: 0.15
  # - name: "Insert"
  #   file: "scooping_insert.yaml"
  #   stop:
  #     measured-velocity-min-threshold: 0.03
  #     desired-velocity-min-threshold: 0.03
  #     contact: false
  #     activation-distance: 0.2
  # - name: "Scoop"
  #   file: "scooping_scoop.yaml"
  #   stop:
  #     measured-velocity-min-threshold: 0.03
  #     desired-velocity-min-threshold: 0.03
  #     contact: false
  #     activation-distance: 0.01
  # - name: "Lift"
  #   file: "scooping_lift.yaml"
  #   stop:
  #     measured-velocity-min-threshold: 0.02
  #     desired-velocity-min-threshold: 0.02
  #     contact: false
  #     activation-distance: 0.15
      
