name: Scraping

required-object-info:
  tool: true
  target-object: true
  task: scraping
  target-object-task: scraping
  tool-task: scraping_butter

# The following motion phases will be executed in a sequence
motion-phases:
  - name: Position Above
    # Giskard file
    file: scraping_position_above.yaml
    # Stop conditions
    stop:
      # When measured gripper velocity drops below this threshold
      measured-velocity-min-threshold: 0.002
      # When desired (set by the controller) gripper velocity drops below this threshold
      desired-velocity-min-threshold: 0.002
      # Stop on contact
      contact: false
      # Ignore stop conditions until the distance 
      # from the target configuration is less than this
      activation-distance: 0.15
  - name: Edge Contact
    file: scraping_edge_contact.yaml
    stop:
      measured-velocity-min-threshold: 0.002
      desired-velocity-min-threshold: 0.002
      contact: true
      activation-distance: 0.15
  - name: Scrape Off
    file: scraping_scrape_off.yaml
    stop:
      measured-velocity-min-threshold: 0.002
      desired-velocity-min-threshold: 0.002
      contact: false
      activation-distance: 0.15
    
